package com.ohmyspark

import org.apache.spark.sql.types._

object Schema {

  val reviewSchema: StructType = new StructType()
    .add("business_id", StringType)
    .add("user_id", StringType)
    .add("date", TimestampType)
    .add("cool", LongType)
    .add("funny", LongType)
    .add("review_id", StringType)
    .add("stars", DoubleType)
    .add("text", StringType)
    .add("useful", LongType)

  val tipSchema: StructType = new StructType()
    .add("business_id", StringType)
    .add("user_id", StringType)
    .add("compliment_count", LongType)
    .add("date", TimestampType)
    .add("text", StringType)

  val photoSchema: StructType = new StructType()
    .add("caption", StringType)
    .add("photo_id", StringType)
    .add("business_id", StringType)
    .add("label", StringType)

  val checkinSchema: StructType = new StructType()
    .add("business_id", StringType)
    .add("date", StringType)

  val userSchema: StructType = new StructType()
    .add("user_id", StringType)
    .add("name", StringType)
    .add("review_count", LongType)
    .add("yelping_since", TimestampType)
    .add("useful", LongType)
    .add("funny", LongType)
    .add("cool", LongType)
    .add("elite", StringType)
    .add("fans", LongType)
    .add("average_stars", DoubleType)
    .add("compliment_hot", LongType)
    .add("compliment_more", LongType)
    .add("compliment_profile", LongType)
    .add("compliment_cute", LongType)
    .add("compliment_list", LongType)
    .add("compliment_note", LongType)
    .add("compliment_plain", LongType)
    .add("compliment_cool", LongType)
    .add("compliment_funny", LongType)
    .add("compliment_writer", LongType)
    .add("compliment_photos", LongType)

  val friendSchema: StructType = new StructType()
    .add("user_id", StringType)
    .add("friends", StringType)

  val hours: StructType = new StructType()
    .add("Monday", StringType)
    .add("Tuesday", StringType)
    .add("Wednesday", StringType)
    .add("Thursday", StringType)
    .add("Friday", StringType)
    .add("Saturday", StringType)
    .add("Sunday", StringType)

  val businessSchema: StructType = new StructType()
    .add("business_id", StringType)
    .add("address", StringType)
    .add("categories", StringType)
    .add("city", StringType)
    .add("hours", hours)
    .add("is_open", IntegerType)
    .add("latitude", DoubleType)
    .add("longitude", DoubleType)
    .add("name", StringType)
    .add("postal_code", StringType)
    .add("review_count", IntegerType)
    .add("stars", DoubleType)
    .add("state", StringType)


  val attributes: StructType = new StructType()
    .add("AcceptsInsurance", StringType)
    .add("AgesAllowed", StringType)
    .add("Alcohol", StringType)
    .add("Ambience", StringType)
    .add("BYOB", StringType)
    .add("BYOBCorkage", StringType)
    .add("BestNights", StringType)
    .add("BikeParking", StringType)
    .add("BusinessAcceptsBitcoin", StringType)
    .add("BusinessAcceptsCreditCards", StringType)
    .add("BusinessParking", StringType)
    .add("ByAppointmentOnly", StringType)
    .add("Caters", StringType)
    .add("CoatCheck", StringType)
    .add("Corkage", StringType)
    .add("DietaryRestrictions", StringType)
    .add("DogsAllowed", StringType)
    .add("DriveThru", StringType)
    .add("GoodForDancing", StringType)
    .add("GoodForKids", StringType)
    .add("GoodForMeal", StringType)
    .add("HairSpecializesIn", StringType)
    .add("HappyHour", StringType)
    .add("HasTV", StringType)
    .add("Music", StringType)
    .add("NoiseLevel", StringType)
    .add("Open24Hours", StringType)
    .add("OutdoorSeating", StringType)
    .add("RestaurantsAttire", StringType)
    .add("RestaurantsCounterService", StringType)
    .add("RestaurantsDelivery", StringType)
    .add("RestaurantsGoodForGroups", StringType)
    .add("RestaurantsPriceRange2", StringType)
    .add("RestaurantsReservations", StringType)
    .add("RestaurantsTableService", StringType)
    .add("RestaurantsTakeOut", StringType)
    .add("Smoking", StringType)
    .add("WheelchairAccessible", StringType)
    .add("WiFi", StringType)

  val businessAttributesSchema: StructType = new StructType()
    .add("business_id", StringType)
    .add("attributes", attributes)


}
